/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emoveisVIEW.view;

import emoveisDAO.ImovelCRUD;
import emoveisMODEL.Imovel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import emoveisVIEW.util.Funcoes;
import emoveisVIEW.view.TelaPrincipal;

/**
 *
 * @author Leandro
 */
public class CadastroImovel extends javax.swing.JFrame {

    /**
     * Creates new form CadastroImovel
     */
    public CadastroImovel() {
        initComponents();
        
        
        //Setando evento ouvinte OnCLose, mostra o menu e fecha a janela atual
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            mostrarMenu();
            dispose();
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoSalvar = new javax.swing.JButton();
        cmbTipo_imovel = new javax.swing.JComboBox<>();
        txtArea_imovel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCor_imovel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQtd_comodos_imovel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEndereconumero_imovel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEnderecocidade_imovel = new javax.swing.JTextField();
        txtEndereco_imovel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEnderecobairro_imovel = new javax.swing.JTextField();
        cmbStatus_imovel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        bntVoltar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtValor_imovel = new javax.swing.JTextField();
        txtEnderecocep_imovel = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela de cadastro");
        setLocationByPlatform(true);
        setResizable(false);

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        cmbTipo_imovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casa", "Apartamento" }));
        cmbTipo_imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipo_imovelActionPerformed(evt);
            }
        });

        txtArea_imovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtArea_imovelKeyReleased(evt);
            }
        });

        jLabel1.setText("Tipo:");

        txtCor_imovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCor_imovelKeyReleased(evt);
            }
        });

        jLabel2.setText("Area:");

        txtQtd_comodos_imovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtd_comodos_imovelKeyReleased(evt);
            }
        });

        jLabel3.setText("Cor:");

        jLabel8.setText("Número:");

        jLabel4.setText("Quantidade de comodos:");

        txtEndereconumero_imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndereconumero_imovelActionPerformed(evt);
            }
        });
        txtEndereconumero_imovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEndereconumero_imovelKeyReleased(evt);
            }
        });

        jLabel5.setText("Endereço");

        jLabel9.setText("Cidade:");

        jLabel6.setText("Bairro:");

        txtEnderecocidade_imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecocidade_imovelActionPerformed(evt);
            }
        });
        txtEnderecocidade_imovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecocidade_imovelKeyReleased(evt);
            }
        });

        txtEndereco_imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndereco_imovelActionPerformed(evt);
            }
        });
        txtEndereco_imovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEndereco_imovelKeyReleased(evt);
            }
        });

        jLabel10.setText("Situação:");

        txtEnderecobairro_imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecobairro_imovelActionPerformed(evt);
            }
        });

        cmbStatus_imovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Disponivel", "Vendido" }));

        jLabel7.setText("CEP:");

        bntVoltar.setText("Voltar");
        bntVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor:");

        txtValor_imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor_imovelActionPerformed(evt);
            }
        });
        txtValor_imovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValor_imovelKeyReleased(evt);
            }
        });

        try {
            txtEnderecocep_imovel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEnderecocep_imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecocep_imovelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(botaoSalvar)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEndereco_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEnderecobairro_imovel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtEndereconumero_imovel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValor_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEnderecocidade_imovel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(txtEnderecocep_imovel))))
                                .addContainerGap(76, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbStatus_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(cmbTipo_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQtd_comodos_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCor_imovel, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtArea_imovel))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cmbTipo_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArea_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCor_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQtd_comodos_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEndereco_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEnderecobairro_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtEnderecocep_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEndereconumero_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEnderecocidade_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntVoltar)
                            .addComponent(botaoSalvar)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(cmbStatus_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(40, 40, 40)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
        String tipo_imovel = cmbTipo_imovel.getSelectedItem().toString();
        int area_imovel = Integer.parseInt(txtArea_imovel.getText());
        String cor_imovel = txtCor_imovel.getText();
        int qtd_comodos_imovel = Integer.parseInt(txtQtd_comodos_imovel.getText());
        String endereco_imovel = txtEndereco_imovel.getText() + ",";
        endereco_imovel += txtEnderecobairro_imovel.getText() + ",";
        endereco_imovel += txtEndereconumero_imovel.getText() + ",";
        endereco_imovel += txtEnderecocep_imovel.getText() + ",";
        endereco_imovel += txtEnderecocidade_imovel.getText();
        double valor_imovel = Double.parseDouble(txtValor_imovel.getText().replaceAll(",", "."));
        boolean status_imovel = (((String)cmbStatus_imovel.getSelectedItem()).equals("Disponivel")) ;
      
        
        Imovel i = new Imovel.ImovelBuilder()
                .tipo_imovel(tipo_imovel)
                .area_imovel(area_imovel)
                .cor_imovel(cor_imovel)
                .qtd_comodos_imovel(qtd_comodos_imovel)
                .endereco_imovel(endereco_imovel)
                .valor_imovel(valor_imovel)
                .status_imovel(status_imovel)
                .build();
        ImovelCRUD.create(i);
        
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
        
        cmbTipo_imovel.setSelectedIndex(0);
        txtArea_imovel.setText("");
        txtCor_imovel.setText("");
        txtQtd_comodos_imovel.setText("");
        txtEndereco_imovel.setText("");
        txtEnderecobairro_imovel.setText("");
        txtEnderecocep_imovel.setText("");
        txtEnderecocidade_imovel.setText("");
        txtEndereconumero_imovel.setText("");
        txtValor_imovel.setText("");
        cmbStatus_imovel.setSelectedIndex(0);
        
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void cmbTipo_imovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipo_imovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipo_imovelActionPerformed

    private void txtEndereconumero_imovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndereconumero_imovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndereconumero_imovelActionPerformed

    private void txtEnderecocidade_imovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecocidade_imovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecocidade_imovelActionPerformed

    private void txtEndereco_imovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndereco_imovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndereco_imovelActionPerformed

    private void txtEnderecobairro_imovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecobairro_imovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecobairro_imovelActionPerformed

    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
        // TODO add your handling code here:
        mostrarMenu();
    }//GEN-LAST:event_bntVoltarActionPerformed
                                        

    private void txtValor_imovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor_imovelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtValor_imovelActionPerformed

    private void txtArea_imovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArea_imovelKeyReleased
        if(!(funcoes.ehNumeroReal(txtArea_imovel.getText()))){
            int tamanho = txtArea_imovel.getText().length();
            txtArea_imovel.setText(txtArea_imovel.getText().substring(0, tamanho-1));
        }
    }//GEN-LAST:event_txtArea_imovelKeyReleased

    private void txtCor_imovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCor_imovelKeyReleased
        if(!(funcoes.ehLetra(txtCor_imovel.getText()))){
            int tamanho = txtCor_imovel.getText().length();
            txtCor_imovel.setText(txtCor_imovel.getText().substring(0, tamanho-1));
        }
    }//GEN-LAST:event_txtCor_imovelKeyReleased

    private void txtQtd_comodos_imovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtd_comodos_imovelKeyReleased
        if(!(funcoes.ehNumeroInteiro(txtQtd_comodos_imovel.getText()))){
            int tamanho = txtQtd_comodos_imovel.getText().length();
            txtQtd_comodos_imovel.setText(txtQtd_comodos_imovel.getText().substring(0, tamanho-1));
        }
    }//GEN-LAST:event_txtQtd_comodos_imovelKeyReleased

    private void txtEndereco_imovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndereco_imovelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndereco_imovelKeyReleased

    private void txtEnderecocep_imovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecocep_imovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecocep_imovelActionPerformed

    private void txtEnderecocidade_imovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecocidade_imovelKeyReleased
        if(!(funcoes.ehLetra(txtEnderecocidade_imovel.getText()))){
            int tamanho = txtEnderecocidade_imovel.getText().length();
            txtEnderecocidade_imovel.setText(txtEnderecocidade_imovel.getText().substring(0, tamanho-1));
        }
    }//GEN-LAST:event_txtEnderecocidade_imovelKeyReleased

    private void txtValor_imovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor_imovelKeyReleased
        if(!(funcoes.ehNumeroReal(txtValor_imovel.getText()))){
            int tamanho = txtValor_imovel.getText().length();
            txtValor_imovel.setText(txtValor_imovel.getText().substring(0, tamanho-1));
        }
    }//GEN-LAST:event_txtValor_imovelKeyReleased

    private void txtEndereconumero_imovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndereconumero_imovelKeyReleased
        if(!(funcoes.ehNumeroInteiro(txtEndereconumero_imovel.getText()))){
            int tamanho = txtEndereconumero_imovel.getText().length();
            txtEndereconumero_imovel.setText(txtEndereconumero_imovel.getText().substring(0, tamanho-1));
        }
    }//GEN-LAST:event_txtEndereconumero_imovelKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroImovel().setVisible(true);
            }
        });
    }
    public void recebeMenu(TelaPrincipal telaPrincipal){
         this.telaPrincipal = telaPrincipal;
    }
    public void mostrarMenu(){
        if(telaPrincipal != null){
            this.dispose();
            telaPrincipal.setVisible(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVoltar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JComboBox<String> cmbStatus_imovel;
    private javax.swing.JComboBox<String> cmbTipo_imovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtArea_imovel;
    private javax.swing.JTextField txtCor_imovel;
    private javax.swing.JTextField txtEndereco_imovel;
    private javax.swing.JTextField txtEnderecobairro_imovel;
    private javax.swing.JFormattedTextField txtEnderecocep_imovel;
    private javax.swing.JTextField txtEnderecocidade_imovel;
    private javax.swing.JTextField txtEndereconumero_imovel;
    private javax.swing.JTextField txtQtd_comodos_imovel;
    private javax.swing.JTextField txtValor_imovel;
    // End of variables declaration//GEN-END:variables
    TelaPrincipal telaPrincipal = new TelaPrincipal();
    Funcoes funcoes = new Funcoes();
}
